config/routes.rb
Rails.application.routes.draw do
  root 'pages#index'
  
  devise_for :users

  resources :charges, only: [:new, :create, :destroy]
  
  resources :users, only: [:show] do
    post '/downgrade' => 'users#downgrade', as: :downgrade
  end
  
  resources :wikis

end

app/models/collaboration.rb
class Collaboration < ActiveRecord::Base
    belongs_to :user
    belongs_to :wiki
end

app/models/user.rb
class User < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  enum role: [:standard, :premium, :admin]
  
  has_many :wikis
  has_many :collaborations
  has_many :shared_wikis, through: :collaborations, source: :wiki
  
  def admin?
    self.role == "admin"
  end

  def premium?
    self.role == "premium"
  end

  def standard?
    self.role == "standard"
  end
         
end

app/models/user2.rb
class User2 < ActiveRecord::Base
  # Include default devise modules. Others available are:
  # :confirmable, :lockable, :timeoutable and :omniauthable
  devise :database_authenticatable, :registerable,
         :recoverable, :rememberable, :trackable, :validatable, :confirmable
         
  has_many :wiki2s
         
  before_save { self.email = email.downcase if email.present? }
end

app/models/wiki.rb
class Wiki < ActiveRecord::Base
  belongs_to :user
  has_many :collaborations
  has_many :users, through: :collaborations
  
  scope :visible_to, -> (user) { user ? all : where(private: false) }
  
  def private?
    self.private
  end
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  include Pundit
  protect_from_forgery with: :exception
  
  #after_action :verify_authorized, except: :index
  #after_action :verify_policy_scoped, only: :index
  
  rescue_from Pundit::NotAuthorizedError, with: :user_not_authorized

private #--------------------------------------------------------

  def user_not_authorized
    flash[:alert] = "You are not authorized to perform this action."
    if current_user.present?
      redirect_to(request.referrer || root_path)
    else
      redirect_to(request.referrer || new_user_session_path)
    end
  end

  
end

app/controllers/chargers_controller.rb
require 'stripe'

class ChargesController < ApplicationController

include Amount

def create
   # Creates a Stripe Customer object, for associating
   # with the charge
   customer = Stripe::Customer.create(
     email: current_user.email,
     card: params[:stripeToken]
   )
 
   # Where the real magic happens
   charge = Stripe::Charge.create(
     customer: customer.id, # Note -- this is NOT the user_id in your app
     amount: Amount.default,
     description: "Blocipedia Premium Membership - #{current_user.email}",
     currency: 'usd'
   )
 
   flash[:notice] = "Thanks for all the money, #{current_user.email}! Feel free to pay me again."
   redirect_to user_path(current_user) # or wherever
 
   # Stripe will send back CardErrors, with friendly messages
   # when something goes wrong.
   # This `rescue block` catches and displays those errors.
   rescue Stripe::CardError => e
     flash[:alert] = e.message
     redirect_to new_charge_path
 end
 
  def new
   @stripe_btn_data = {
     key: "#{ Rails.configuration.stripe[:publishable_key] }",
     description: "BigMoney Membership - #{current_user.name}",
     amount: Amount.default
   }
 end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def index

  end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  
  def show
    @user = User.find(params[:id])
  end

  def downgrade
    @user = User.find(params[:user_id])
    @user.standard!
    redirect_to :back
  end
  
end

app/controllers/wikis_controller.rb
class WikisController < ApplicationController
  
  #before_action :require_sign_in, except: [:index, :show]
  
  def index
    @wikis = policy_scope(Wiki)
  end

  def show
    @wiki = Wiki.find(params[:id])
    authorize @wiki

  end

  def new
    @wiki = Wiki.new
    authorize @wiki
    
    @other_users = User.all - [current_user]
  end

  def create
    @wiki = Wiki.new(wiki_params)
    @wiki.user = current_user
    authorize @wiki
    
    if @wiki.save
      flash[:notice] = "Wiki was saved."
      redirect_to @wiki
    else
      flash[:error] = "There was an error saving your Wiki. Please try again."
      render :new
    end
  end
  
  def edit
    @wiki = Wiki.find(params[:id])
    authorize @wiki
    
    @other_users = User.all - [current_user]
  end
  
  def update
    @wiki = Wiki.find(params[:id])
    @wiki.assign_attributes(wiki_params)
    authorize @wiki
    
 
    if @wiki.save
      flash[:notice] = "Wiki was updated successfully."
      redirect_to @wiki
    else
      flash.now[:alert] = "There was an error saving your Wiki. Please try again."
      render :edit
    end
  end
  
   def destroy
     @wiki = Wiki.find(params[:id])
     authorize @wiki
 
     if @wiki.destroy
       flash[:notice] = "\"#{@wiki.title}\" was deleted successfully."
       redirect_to @wiki
     else
       flash.now[:alert] = "There was an error deleting the wiki."
       render :show
     end
   end
   
   # private method
   private
   
   def wiki_params
     params.require(:wiki).permit(:title, :body, :private)
   end
end

app/helpers/application_helper.rb
module ApplicationHelper
    
  def form_group_tag(errors, &block)
    css_class = 'form-group'
    css_class << ' has-error' if errors.any?

    content_tag :div, capture(&block), class: css_class
  end
    
  def markdown(text)
    options = {
      filter_html: true,
      hard_wrap: true
    }

    extensions = {
      autolink: true,
      superscript: true,
      disable_indented_code_blocks: true
    }

    renderer = Redcarpet::Render::HTML.new(options)
    markdown = Redcarpet::Markdown.new(renderer, extensions)

    markdown.render(text).html_safe
  end
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/helpers/wikis_helper.rb
module WikisHelper
end

app/views/charges/new.html.erb
<%= form_tag charges_path do %>
   <h4>Click the button!</h4>
   <script class='stripe-button' src="https://checkout.stripe.com/checkout.js" data-key="<%= @stripe_btn_data[:key] %>" data-amount=<%= @stripe_btn_data[:amount] %> data-description="<%= @stripe_btn_data[:description] %>" ></script>
<% end %>

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Workspace</title>
  <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track' => true %>
  <%= javascript_include_tag 'application', 'data-turbolinks-track' => true %>
  <%= csrf_meta_tags %>
</head>
<body>
  
   <ul>
       <li><%= link_to "Blocipedia", root_path %></li>
       
       <div class="pull-right user-info">
         <% if user_signed_in? %>
           Signed in as: <strong><%= link_to current_user.name, user_path(current_user.id), :class => 'navbar-link' %></strong> - <%= link_to "Sign Out", destroy_user_session_path, method: :delete, :class => 'navbar-link'  %>
             <% if current_user.standard? %>
               <%= link_to "Upgrade", new_charge_path, class: 'btn btn-success' %>
             <% end %>
           <%= link_to 'Edit profile', edit_user_registration_path, :class => 'navbar-link' %>
           <%= link_to 'Cancel profile', cancel_user_registration_path, :class => 'navbar-link' %>
         <% else %>
           <%= link_to "Sign In", new_user_session_path, :class => 'navbar-link'  %>
           <%= link_to "Sign Up", new_user_registration_path, :class => 'navbar-link'  %>
         <% end %>
       </div>
   </ul>
   
   <div class="flash">
    <% if flash[:notice] %>
    <div class="alert alert-success">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:notice] %>
    </div>
    <% elsif flash.now[:alert] %>
    <div class="alert alert-danger">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash.now[:alert] %>
    </div>
    <% elsif flash[:alert] %>
    <div class="alert alert-warning">
      <button type="button" class="close" data-dismiss="alert">&times;</button>
      <%= flash[:alert] %>
    </div>
    <% end %>
   </div>
  
<%= yield %>

</body>
</html>

app/views/pages/index.html.erb
<h1>Blocipedia</h1>
<p>Come collaborate with fellow people on public and private Wikis!</p>

app/views/users/show.html.erb
<h1>User Page</h1>

<div class="row">
  <div class="col-md-4">
    User Name:
  </div>
  <div class="col-md-1">
    <%= @user.name %>
  </div>
</div>
<div class="row">
  <div class="col-md-4">
    User Email:
  </div>
  <div class="col-md-1">
    <%= @user.email %>
  </div>
</div>
<div class="row">
  <% if @user.standard? %>
    <%= link_to "Upgrade", new_charge_path , class: 'btn btn-success' %>
  <% else %>
    <%= link_to "Downgrade", user_downgrade_path(current_user.id), class: 'btn btn-success', method: :post %>
  <% end %>
</div>

app/views/wikis/_form.html.erb
<%= form_for @wiki do |f| %>
  <% if wiki.errors.any? %>
  <div class="alert alert-danger">
    <h4><%= pluralize(wiki.errors.count, "error") %>.</h4>
    <ul>
      <% wiki.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
    </ul>
  </div>
  <% end %>

  <%= form_group_tag(wiki.errors[:title]) do %>
     <%= f.label :title %>
     <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
  <% end %>
  <%= form_group_tag(wiki.errors[:body]) do %>
     <%= f.label :body %>
     <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
  <% end %>
  <% if current_user.admin? || current_user.premium? %>
    <div class="form-group" >
      <%= f.label :private, class: 'checkbox' do %>
        <%= f.check_box :private %> Private wiki
      <% end %>
    </div>
  <% end %>
  <div class="form-group">
    <%= f.submit "Save", class: 'btn btn-success' %>
  </div>
<% end %>

app/views/wikis/edit.html.erb
<h1>Edit Wiki</h1>
 
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
     
     <% if current_user.admin? || current_user.premium? %>
       <div class="form-group">
         <%= f.label :private, class: 'checkbox' do %>
           <%= f.check_box :private %> Private wiki
         <% end %>
       </div>
     <% end %>
   </div>

app/views/wikis/index.html.erb
<h1>Wikis</h1>

<div class="row">
  <!--<% @wikis.each do |wiki| %>-->
  <% policy_scope(@user.wikis).each do |wiki| %>
    <div class="media">
      <div class="media-body">
        <h4 class="media-heading">
          <div class="col-md-4">
            <%= link_to wiki.title, wiki %>
          </div>
          <div class="col-md-1">
           <% if policy(wiki).edit? %>
            <%= link_to "edit", edit_wiki_path(wiki), class: 'btn btn-success'  %>
           <% end %>
          </div>
          <div class="col-md-1">
           <% if policy(wiki).destroy? %>
            <%= link_to "delete",  wiki, method: :delete, class: 'btn btn-danger', data: { confirm: 'Are you sure you want to delete this wiki?'} %>
           <% end %>
          </div>
        </h4>
      </div>
    </div>
  <% end %>

  <div class="col-md-4">
    <%= link_to "New Wiki", new_wiki_path, class: 'btn btn-success' %>
  </div>
</div>

app/views/wikis/new.html.erb
<h1>New Wiki</h1>
 
   <div class="col-md-8">
     <%= form_for @wiki do |f| %>
       <div class="form-group">
         <%= f.label :title %>
         <%= f.text_field :title, class: 'form-control', placeholder: "Enter wiki title" %>
       </div>
       <div class="form-group">
         <%= f.label :body %>
         <%= f.text_area :body, rows: 8, class: 'form-control', placeholder: "Enter wiki body" %>
       </div>
       <div class="form-group">
         <%= f.submit "Save", class: 'btn btn-success' %>
       </div>
     <% end %>
     
     <% if current_user.admin? || current_user.premium? %>
       <div class="form-group">
         <%= f.label :private, class: 'checkbox' do %>
           <%= f.check_box :private %> Private wiki
         <% end %>
       </div>
     <% end %>
   </div>

app/views/wikis/show.html.erb
<div>
  <h1>
    <%= markdown(@wiki.title) %><br>
  </h1>
</div>
 
 <div class="row">
   <div class="col-md-8">
     <p><%= markdown(@wiki.body) %></p>
   </div>
   <div class="col-md-4">
    <% if policy(@wiki).update? %>
     <%= link_to "Edit", edit_wiki_path(@wiki), class: 'btn btn-success' %>
    <% end %>
    <% if policy(@wiki).destroy? %>
     <%= link_to "Delete Wiki", @wiki, method: :delete, class: 'btn btn-danger', data: {confirm: 'Are you sure you want to delete this wiki?'} %>
    <% end %>
   </div>
 </div>